spring:
  application:
    name: notification
  cloud:
    function:
      definition: orderCreated  # Identified and registered as a function
    stream:
      function:
        definition: orderCreated
      bindings:
        orderCreated-in-0:
          destination: order-exchange
          group: notification-group
          content-type: application/json
      kafka:
        binder:
          brokers: kafka:9092

server:
  port: 8084