spring:
  application:
    name: notification
  cloud:
    function:
      definition: orderCreated  # Identified and registered as a function
    stream:
      function:
        definition: orderCreated
      bindings:
        orderCreated-in-0:
#          destination: order-exchange.new
          destination: order-exchange
#          group: notification-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

#  rabbitmq:
#    host: ${RABBITMQ_HOST:localhost}
#    port: ${RABBITMQ_PORT:5672}
#    username: ${RABBITMQ_USERNAME:guest}
#    password: ${RABBITMQ_PASSWORD:guest}
#    virtual-host: ${RABBITMQ_VHOST:guest}
#    connection: 30000 #millisecond
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

#rabbitmq:
#  exchange:
#    name: order.exchange
#  queue:
#    name: order.queue
#  routing:
#    key: order.tracking


server:
  port: 8084