spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
#      uri: mongodb+srv://hayyith123:67702121H@user-data.ksfceki.mongodb.net/?retryWrites=true&w=majority&appName=user-data
      database: ecom_user
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection: 30000 #millisecond

#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: hayyith
#    password: hayyith
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

logging:
  file:
    name: logs/${spring.application.name}.log
    logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7



server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0



eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true

# KEYCLOAK
keycloak:
  admin:
    username: user
    password: user
    server-url: http://localhost:8443
    realm: ecom-app
    client-id: admin-cli
    client-uid: 3ecb4ab8-2874-46e1-a65b-d4f45697617d