spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ecom_user
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection: 30000 #millisecond

logging:
  file:
    name: logs/${spring.application.name}.log
    logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}

eureka:
  client:
    serviceUrl:
      defaultZone: "http://eureka:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true

# KEYCLOAK
keycloak:
  admin:
    username: user
    password: user
    server-url: http://keycloak:8443
    realm: ecom-app
    client-id: admin-cli
    client-uid: 3ecb4ab8-2874-46e1-a65b-d4f45697617d