spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:\Spring_Boot_Notes\microservices_Project\configserver\src\main\resources\config
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection: 30000 #millisecond

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

